### ISSUE TITLE
You can publish a Release?

### ISSUE THREAD

**Issue by GabrielAugustoTI** [graywolf336/Rocket.Chat.Minecraft#7]
I want test it, but is not compiled, and i no have time for compile, you can publish .jar as release?

**Comment by graywolf336** [comment]
Hey thanks for showing interest! Actually there's a build server which builds everytime a push to the `develop` branch happens. https://ci.craftyn.com/job/Rocket.Chat.Minecraft/

If you do end up using it, let me know how it goes and also what features you'd like to see added. :)
